http:
  port: 18080
spring:
  datasource:
    name: development
    url: jdbc:mysql://10.66.42.19:3306/hatc1.1_test4
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  rabbitmq:
    host: 10.66.42.24
    port: 5672
    virtual-host: /spoon
    username: spoon
    password: spoon
    publisher-confirms: true